### ISSUE TITLE
GitHub Actionsによる複数ランタイム互換性テスト・設定の自動化

### ISSUE THREAD

**Issue by masinc** [masinc/deno-ndl#28]
## 概要

JSRの「At least two runtimes are marked as compatible」要件を満たすため、GitHub Actionsを使用して複数ランタイムでの動作確認とJSR設定の自動化を実装する。

## 背景

現在JSRスコアで「Missing score: At least two runtimes are marked as compatible」となっている。
- Issue #27でコード側のランタイム互換性は確保済み（Web Standards APIのみ使用）
- JSR設定での複数ランタイム対応マークが必要

### 1. 複数ランタイムでのテスト実行

- [ ] **Deno**: 既存のテスト環境（deno test）
- [ ] **Node.js**: npm/yarn経由でのテスト実行
- [ ] **Bun**: bunでのテスト実行
- [ ] GitHub Actions Matrix戦略での並列実行

### 2. ビルド・変換プロセス

- [ ] **TypeScript→JavaScript変換**: 各ランタイム用
- [ ] **Import Map変換**: Deno → Node.js/Bun用のパス解決
- [ ] **Package.json生成**: Node.js互換性のため
- [ ] **Dependencies解決**: npm:zodからzodへの変換

### 3. JSR設定自動化

- [ ] **Runtime Compatibility API**: JSRのruntime compatibility設定
- [ ] **CI/CD Integration**: テスト成功時の自動設定更新
- [ ] **Badge/Status表示**: README等での互換性表示

### 4. 開発環境改善

- [ ] **Local Testing**: 開発者がローカルで複数ランタイムテスト可能
- [ ] **Documentation**: 複数ランタイム対応の手順書
- [ ] **Examples**: 各ランタイムでの使用例

### ランタイム間の差異対応

```typescript
// Deno
import { z } from "zod/v4";  // npm: specifier

// Node.js/Bun  
import { z } from "zod";     // 標準npm package
```

### テストコマンド統一

```yaml
# GitHub Actions例
strategy:
  matrix:
    runtime: [deno, node, bun]
    
steps:
  - name: Test with ${{ matrix.runtime }}
    run: |
      case ${{ matrix.runtime }} in
        deno) deno task test ;;
        node) npm test ;;
        bun) bun test ;;
      esac
```

## 期待効果

- **JSRスコア向上**: 94% → 95%+ (runtime compatibility +1点)
- **開発者信頼性**: 複数環境での動作保証
- **採用促進**: より幅広いプロジェクトでの利用可能
- **CI/CD改善**: 自動化されたクロスランタイムテスト

## 優先度

- **Priority**: Medium-High
- **Effort**: Large (複数ワークフローの設計・実装)
- **Impact**: High (JSR互換性とエコシステム対応)

## 関連Issue

- #27: JSRスコア改善（コード側互換性は完了）

## 参考資料

- [JSR Runtime Compatibility](https://docs.jsr.io/publishing-packages#runtime-compatibility)
- [GitHub Actions Matrix Strategy](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs)
- [Deno to Node.js Compatibility Guide](https://deno.land/manual/node)
